name: EventSphere CI/CD Pipeline with Conditional Logic

on:
  push: # Run the workflow when changes are pushed to specific branches
    branches:
      - main          # Trigger on pushes to the main branch
      - feature/*     # Trigger on pushes to branches starting with 'feature/'
  pull_request: # Run the workflow when a pull request targets the main branch
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest 
    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3 

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3 
        with:
          node-version: '16'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test

  continuous-deployment:
    needs: continuous-integration # This job depends on the successful completion of the 'continuous-integration' job
    runs-on: ubuntu-latest 
    # Conditional logic: Only run this job if the branch is 'main' or if the workflow is triggered by a tag
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') 

    steps:
      # Step 5: Deployment step
      - name: Deploy to production
        run: |
          echo "Deploying application to production..." # Placeholder for deployment command
          echo "Deployment complete!" # Placeholder for deployment success message
